name: Flutter CI/CD

on:
  pull_request:
    branches:
      - main
jobs:
  flutter_test:
    name: Run flutter analyze and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses:  subosito/flutter-action@v2.21.0
        with:
           channel: 'stable'
      - run: flutter pub get
      - run: flutter test

  build_ios:
    name: Build Flutter iOS
    needs: [flutter_test]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses:  subosito/flutter-action@v2.21.0
        with:
           channel: 'stable'
      - run: flutter clean
      - run: flutter pub get
      - run: flutter build ios --no-codesign

  build_appbundle:
    name: Build Flutter App Bundle (Android)
    needs: [ flutter_test ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: subosito/flutter-action@v2.21.0
        with:
          channel: 'stable'
          # flutter-version: '3.16.8'
          # If you want to use a specific version of flutter
      - run: flutter clean
      - run: flutter pub get
      - run: flutter build appbundle